### PR TITLE
Update roadmap UX

### PR DESCRIPTION
**Pull request by dlesaca**
- Move roadmap link to top-level of navigation
- Update roadmap page

### CODE REVIEW

**Comment by asurve** [comment]
Please do not remove changes specific to earlier releases like 0.9 to 0.13.

**Comment by asurve** [comment]
LGTM

**Comment by deroneriksson** [comment]
Thank you @dlesaca! I'll merge

**Comment by asurve** [comment]
thanks @dlesaca & @deroneriksson

**Pull request closed without merging**
