### PR TITLE
[MINOR] Update download page for release 0.13

### PR DESCRIPTION
**Pull request by gweidner**
Updated project version and text in download page.

### CODE REVIEW

**Comment by gweidner** [comment]
Marked as WIP since can't be merged until IPMC vote completes.

**Comment by gweidner** [comment]
Additional release notes to be addressed in separate PR.

**Comment by gweidner** [comment]
Vote has been approved by IPMC:
https://www.mail-archive.com/general@incubator.apache.org/msg58834.html

**Comment by deroneriksson** [comment]
LGTM. Thank you @gweidner. Please feel free to merge when appropriate.

**Comment by gweidner** [comment]
Thank you @deroneriksson for reviewing!  I will merge to git repo, but after merging, could you update svn since my account has not yet been granted access?

**Comment by deroneriksson** [comment]
Sure!

**Comment by asurve** [comment]
Instead of Spark 2.1, it should be Spark 2.0.2 and above.

**Comment by gweidner** [comment]
I'll update 2.1 -> '2.0.2 and above' as part of PR #41.  Thanks for reviewing and updating svn.

**Pull request closed without merging**
