### PR TITLE
[SYSTEMML-893] Update project team members page design

### PR DESCRIPTION
**Pull request by lresende**
Utilize github id to display contributor picture.
Below is how the new design looks like.

systemml team members

### CODE REVIEW

**Comment by lresende** [comment]
@deroneriksson @dusenberrymw Could you please review.

**Comment by deroneriksson** [comment]
Hi @lresende. I believe I just saw that a new redesign that will be ready in the next couple days totally redesigns the main page and also the team page. So I believe the HTML will be quite different in a couple days.

The contributors.yml page looks like a nice way to store the contributor information. We will need to update the githubId values for each user since they are quite often different from the apacheId values (ie, deron vs deroneriksson)

This looks great but I expect we will have some additional significant updates coming in the next couple days.

**Comment by lresende** [comment]
Yes, when the new design is ready we update the page, but the data will help with the page.

**Comment by lresende** [comment]
I have also reviewed the githubids, and fixed couple mismatches.

**Comment by deroneriksson** [comment]
I agree, the data will definitely help with the page. Thank you @lresende. LGTM

**Comment by lresende** [comment]
Merged.

**Pull request closed without merging**
