### PR TITLE
[SYSTEMML-1098] Make file names direct hyperlinks in Downloads Page

### PR DESCRIPTION
**Pull request by jazares**
make file names hyperlinks for direct download

### CODE REVIEW

**Comment by lresende** [comment]
-1 
There is a requirement to go over the mirrors, and the script will help identify the closest mirror, etc... we should not have a direct link...

**Comment by deroneriksson** [comment]
@lresende @jazares 
I think this PR should be great if @jazares could replace the direct mirror links with the apache mirror links, by replacing the direct hosts with http://www.apache.org/dyn/closer.cgi/...

**Comment by jazares** [comment]
@lresende @deroneriksson removed the archive column and made file title a hyperlink to the mirrors page

**Comment by deroneriksson** [comment]
@lresende @jazares 
I validated that the download hyperlinks now go to the apache mirrors pages.
LGTM. I'll merge.

**Comment by deroneriksson** [comment]
I created a new JIRA issue for this PR to address the consolidation of the name and archive columns. ([SYSTEMML_1100] Consolidate name and archive columns for download links)

**Comment by deroneriksson** [comment]
@jazares BTW, sorry for the confusion, but would you mind renaming this PR to [SYSTEMML_1100] Consolidate name and archive columns for download links? 1098 is closed and I created 1100 to be more descriptive.

**Comment by deroneriksson** [comment]
@lresende Looking back at the discussion, sorry for merging with the -1. The focus of the PR changed and I should have handled the change in a separate PR.

**Comment by deroneriksson** [comment]
Thanks @jazares!

**Pull request closed without merging**
