### PR TITLE
[SYSTEMML-1054] Refactor Get Started Page with CSS Updates

### PR DESCRIPTION
**Pull request by jazares**
- Made CSS containers smaller. 
- applied grid to tutorial instructions

### CODE REVIEW

**Comment by dusenberrymw** [comment]
@jazares I think the same issue is going on here as with that other merged PR -- please always create new branches while on an updated `master` branch, rather than a previously used branch.  Otherwise, these old commits will show up, and thus the merging will be more difficult.

```
// time to start working on a new PR
// checkout and update your laptop's master branch
git checkout master
git pull upstream master
// create a new branch for the new PR
git checkout -b myCoolNewBranch
```

**Comment by dusenberrymw** [comment]
One way to start working on a new PR using the code from an open PR before it is merged, without running into conflicts, is to start on that open PR's branch, make all the changes without making any commits, and then stash them away once the open PR has been merged.  Then you can simply use the above steps to create a new PR (which will have the code of that merged PR that you need), and the "unstash" those other change on top of it.  Speeds up the iteration time.

```
// currently waiting on an open PR to be merged, and want to work on the next PR now, making use of this code
// assuming your on the open PR's branch:
// make code changes, but don't commit anything...
// Now the open PR has been merged -- time to stash, and create a new branch
git stash
git checkout master
git pull upstream master
git checkout -b myCoolNewBranch
git stash apply
// check that everything looks good
// commit, push, create a new PR
```

**Comment by dusenberrymw** [comment]
cc @dlesaca cool trick above as well

**Comment by dusenberrymw** [comment]
Ah okay so I figured out the issue.  It's recommended when you're working on a PR to only update from the master prior to starting using the `git pull upstream master`.  Then, while working on a branch, it's best not to use that command again.  Otherwise, the newer commits from master end up all interleaved together and you'll have "merge" commits, which are difficult to squash later on.  It's best to simply work on the copy that you started with, then periodically squash those commits down to 1 commit, the rebase on top of the latest master using `git pull --rebase upstream master`, the force push to the PR with `git push --force` (careful with this later one).

Flow:

```
// time to start working on a new PR
// checkout and update your laptop's master branch
git checkout master
git pull upstream master
// create a new branch for the new PR
git checkout -b myCoolNewBranch
// work and make commits and make PR
// ....
// squash a bunch of mini commits together
// make a quick backup for safety
git branch myBackup1
git rebase -i HEAD~NUMBEROFCOMMMITSTOSQUASH
// -> on ensuing screen, other than the first "pick", change all other commits you made to "squash" and exit that screen
// now all your work should be in one commit
// rebase onto latest master, fixing any conflicts along the way (use guide on other PR)
git pull --rebase upstream master
// update PR
git push --force
```

cc @deroneriksson

**Comment by dlesaca** [comment]
@dusenberrymw  We need to `git push --force` evertime? Just trying to clarify because we keep getting warned about this ominous `git push --force` guy.

**Comment by dusenberrymw** [comment]
@dlesaca No, the `git push --force` is __only__ for when you've already created a PR, have merge conflicts, have to do a `git pull --rebase upstream master` to resolve the conflicts, are certain that you're local copy is now correct, and now have to update the PR.

**Comment by dusenberrymw** [comment]
Also, just to clarify, once you've started working on a new branch and have committed things to it, never use `git pull upstream master`.  That command is only good for updating your laptop's `master` branch **before** creating a new branch.  Otherwise it simply merges new updates from the project on top of your local branch's commits, thus placing them out of order.  If you'd like to make use of new updates to the project on your branch, please use `git pull --rebase upstream master` and the above guide.

**Comment by deroneriksson** [comment]
@dlesaca The force says to take what you have locally and to overwrite what's on the remote copy of the branch. It means that what you have locally is the correct copy of what should be on the branch, and you want the remote branch to reflect that. Since the commit SHAs are different, the force is required.

The "push --force" is powerful but is mostly a scary command for committers who are merging code into the apache master branch.

**Comment by jazares** [comment]
@dusenberrymw The conflicts should be resolved

**Pull request closed without merging**
