### PR TITLE
[SYSTEMML-962] Refactor jekyll based website with new layout

### PR DESCRIPTION
**Pull request by lresende**
Apply the new website layout to the existing Jekyll based website.

### CODE REVIEW

**Comment by lresende** [comment]
@deroneriksson @objectadjective The main entry page seems to be working well, except for the videos. And I need to fix some styles on the old pages. But other then that it seems to be coming along well. Please provide some feedback on things that I might have missed.

**Comment by deroneriksson** [comment]
@lresende This is great! Thank you for all the hard work migrating the new design to Jekyll! This is a huge step forward for the project.

When viewing the generated source code, I noticed that this version fixes the favicon image. Does that mean that this represents the most up-to-date official version of the website since it contains improvements such as the favicon fix (compared to what is in svn)?

I noticed that the "Get Involved" header isn't centered on Chrome but that is very minor and we can subsequently update little things such as that. The important thing is that we now have the redesign migrated to Jekyll which is awesome. 

LGTM.

**Comment by objectadjective** [comment]
@lresende Thanks, this is awesome.

**Comment by dlesaca** [comment]
@lresende LGTM

**Comment by lresende** [comment]
Merged into master.

**Pull request closed without merging**
