### PR TITLE
Issue61/design

### PR DESCRIPTION
**Pull request by objectadjective**
Update Install SystemML page copy.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Hi @objectadjective. I'm having a little difficulty determining how to merge PR's 50, 51, and 52 since they contain overlapping commits (usually I follow a workflow such as the following http://apache.github.io/incubator-systemml/contributing-to-systemml.html#systemml-on-github). I think it might be easier if PR's 50, 51, and 52 were closed and a single new combined PR were created (after pulling the latest from master). This PR could contain all the updates so that no questions regarding merging occur. Also, I think this would make giving feedback easier.

@dusenberrymw What are your thoughts?

**Comment by objectadjective** [comment]
Sorry, I think if you merge them in order, it should be fine.

**Comment by deroneriksson** [comment]
@dusenberrymw Could you please take a look at this? For instance, for https://github.com/apache/incubator-systemml-website/pull/51/files, I am not seeing the updates such as the update to the title/description of install-systemml.html. So I'm not really sure how to give feedback if these are separate PRs with combined commits without potentially making merge conflicts.

**Comment by dusenberrymw** [comment]
Do we want to have the notebooks on the homepage?  I was thinking that once we condensed the "getting started" page down to almost nothing, the notebooks could be included there.

Also, it looks like the icons at the bottom (github, twitter, etc.) have become distorted in this PR.

**Comment by objectadjective** [comment]
I included the notebooks on both the homepage and get started. I don't see any distortion in the social icons. None of that code should have been effected. What browser are you seeing this?

**Pull request closed without merging**
