### PR TITLE
[SYSTEMML-1050] Refactor Tutorials Page After Design Update

### PR DESCRIPTION
**Pull request by jazares**
Refactor Tutorials Page After Design Update

SYSTEMML-972 Refactor Jekyll website based on new page layout / SYSTEMML-1050

### CODE REVIEW

**Comment by lresende** [comment]
Could you please update the PR title and add the jira, like:
[SYSTEMML-XXX] Fooooo

Also, you need to rebase and update the PR as it's currently conflicting and cannot be merged

**Comment by jazares** [comment]
@lresende Thanks, all fixed.

**Comment by deroneriksson** [comment]
Sure @dlesaca I will take a look now.

**Comment by deroneriksson** [comment]
@jazares @dlesaca 
Right now it doesn't appear to be rendering correctly for me when I examine the PR. It might have to do the order of the commits:
```
Jason Azares  (2016-10-21): cleaned up conflicts with upstream/master
Jason Azares  (2016-10-20): refactored tutorials page with updated CSS.
Jason Azares  (2016-10-20): [SYSTEMML-1049] Refactor the homepage with updated CSS styling
Jason Azares  (2016-10-20): refactored the homepage with updated CSS stylings
```
The "[SYSTEMML-1049]" commit appears above the "refactored the homepage..." rather than below it.
@lresende @dusenberrymw Any suggestions how to fix?

**Comment by dusenberrymw** [comment]
I'll take a look right now.

**Comment by dusenberrymw** [comment]
@jazares Merged.  The Git stuff was a bit weird in this PR due to the ["refactored the homepage with updated CSS stylings"](https://github.com/apache/incubator-systemml-website/pull/9/commits/21e9e3029b5d7101ef5b6d684be1a46debcb0491) commit having the same content of the recently merged commit ["[SYSTEMML-1049] Refactor the homepage with updated CSS styling"](https://github.com/apache/incubator-systemml-website/commit/b2dcd0a110914e6387140be53c83ab06a35c0925).  This may have been due to starting work on this PR by creating a new branch on your laptop off of the "home-page" branch used in #8.  If that was the case, I'd recommend always creating a new branch off of an updated "master" branch:

```
git checkout master
git pull upstream master
git checkout -b myCoolNewBranchForSomeAwesomeNewWork
```

👍

**Comment by deroneriksson** [comment]
I'm currently experiencing problems connecting to github.com because of the DDoS attack. Mike, if you can connect, can you take a look? 
 
----- Original message -----From: Dexter Lesaca <notifications@github.com>To: apache/incubator-systemml-website <incubator-systemml-website@noreply.github.com>Cc: Deron Eriksson/San Francisco/IBM@IBMUS, Mention <mention@noreply.github.com>Subject: Re: [apache/incubator-systemml-website] [SYSTEMML-1050] Refactor Tutorials Page After Design Update (#9)Date: Fri, Oct 21, 2016 10:02 AM 
@dusenberrymw @deroneriksson Will you guys take a look at this, please?

**Pull request closed without merging**
