### PR TITLE
[MINOR] Add roadmap information for 0.12 release

### PR DESCRIPTION
**Pull request by gweidner**
Added roadmap information for 0.12 release following pattern observed for previous release.  Content based on manually checking commits since 0.11 release due to inconsistent fixed-in version of resolved JIRAs.

### CODE REVIEW

**Comment by gweidner** [comment]
Tested by displaying changes in local web browser following instructions in readme.

**Comment by deroneriksson** [comment]
Welcome to the SystemML website! LGTM. Let me know if you need any assistance merging into git and then svn (commiting to svn actually publishes the content).

**Comment by asurve** [comment]
LGTM

**Comment by deroneriksson** [comment]
Thanks @gweidner! I'll merge this since I'm making some other updates too.

**Comment by gweidner** [comment]
Thank you @deroneriksson - much appreciated!

**Pull request closed without merging**
